simulation:
  area_size: 'small'
  max_steps: 100
  seed: 42
  save_data: true
  save_location: "~/results"

fire:
  initial_fires: 1
  model: 'simple'

swarm:
  initial_bases: 1

  drone_base:
    number_of_agents: 30

# TODO: should this be in km? and scaled in the loading process?
  drone:
    battery_capacity: 70
    battery_movement_cost: 1
    battery_hovering_cost: 0.5
    battery_low_threshold: 20
    battery_recharge_rate: 5
    communication_range: 15
    vision_range: 5
