simulation:
  area_size: 'large'
  max_steps: 100
  seed: 42
  save_data: true
  save_location: "~/results"

fire:
  initial_fires: 1
  model: 'simple'

swarm:
  initial_bases: 2

  drone_base:
    number_of_agents: 50

  drone:
    battery_capacity: 70
    battery_consumption_per_cell: 1
    communication_range: 15
    vision_range: 5
